version: "3.8"

services:
  comics-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data  # Подключаем папку data как volume
    ports:
      - "5000:5000"  # Пробрасываем порт 5000 для Flask
    container_name: comics-app-container
