version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    container_name: flask-app-container